import Head from 'next/head'
import React from 'react';
import prisma from '../../lib/prisma';
import { Post } from '../../views/post';
import { Comment } from '../../views/comment';

export async function getStaticPaths(ctx) {
    const posts = await prisma.post.findMany();

    const paths = posts.map(post => ({
        params: { id: post.id.toString() }
    }));

    return {
        paths,
        fallback: false
    }
}

export async function getStaticProps({ params }) {
    const post = await prisma.post.findUnique({
        where: { id: parseInt(params.id) },
        include: { author: true }
    });

    const comments = await prisma.comment.findMany({
        where: { postId: post.id },
        include: { author: true }
    });

    const postD = new Post(post).toDto();
    const commentsD = comments.map(c => (new Comment(c)).toDto());


    return {
        props: {
            post: postD,
            comments: commentsD
        }
    }
}

function CommentView({ comment }) {
    return (
        <div>
            <p>{comment.author.username}</p>
            <p>{comment.content}</p>
        </div>
    )
}

export default function PageView({ post, comments }) {
    return (
        <div>
            <Head>
                <title>{post.title}</title>
                <meta name="description" content="Generated by post" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main>
                <h1>{post.title}</h1>
                <p>{post.content}</p>
            </main> 

            {comments.map(comment => (
                <CommentView key={comment.id} comment={comment} />
            ))}
        </div>
    )
}
