import Head from 'next/head'
import React from 'react';
import { useRouter } from 'next/router';
import prisma from '../../lib/prisma';
import { Post } from '../../views/post';

export async function getStaticPaths(ctx) {
    const posts = await prisma.post.findMany();

    const paths = posts.map(post => ({
        params: { id: post.id.toString() }
    }));

    return {
        paths,
        fallback: false
    }
}

export async function getStaticProps({ params }) {
    const post = await prisma.post.findUnique({
        where: { id: parseInt(params.id) },
        include: { author: true, comments: true }
    });

    const postD = new Post(post).toDto();

    return {
        props: {
            post: postD
        }
    }
}

export default function PageView({ post }) {
    return (
        <div>
            <Head>
                <title>{post.title}</title>
                <meta name="description" content="Generated by post" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main>
                <h1>{post.title}</h1>
                <p>{post.content}</p>
            </main> 
        </div>
    )
}
